# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files in .github/workflows will be checked
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies"]

  - package-ecosystem: "pip"
    directory: "docs/"
    schedule:
      interval: "daily"
    labels: ["dependencies", "documentation"]
    reviewers: ["mcflugen"]

  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "daily"
    labels: ["dependencies", "documentation"]
    reviewers: ["mcflugen"]
