repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    language_version: python3
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi]
  - id: black-jupyter
    name: black-jupyter
    description:
      "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
    entry: black
    language: python
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi, jupyter]
    additional_dependencies: [".[jupyter]"]

- repo: https://gitlab.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    # additional_dependencies: [flake8-bugbear]

- repo: https://gitlab.com/iamlikeme/nbhooks
  rev: 1.0.0
  hooks:
  - id: nb-ensure-clean
    name: nb-ensure-clean
    description: Ensure that committed Jupyter notebooks contain no outputs.
    entry: nb-ensure-clean
    files: \.ipynb$
    language: python
    language_version: python3

- repo: https://github.com/asottile/pyupgrade
  rev: v2.34.0
  hooks:
  -   id: pyupgrade
      args: [--py38-plus]

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      files: \.py$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-builtin-literals
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: trailing-whitespace

- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.1.1
  hooks:
    - id: pydocstyle
      files: src/bmi_wavewatch3/.*\.py$
      args:
        # - --convention=numpy
        - --select=D417
