version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  install:
    - requirements: docs/requirements.txt

    - method: pip
      path: .
  system_packages: false

build:
  image: latest
  tools:
    python: "3.11"
