version: 2

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  version: 3.8
  install:
    - method: pip
      path: ".[doc]"
  system_packages: false

build:
  image: latest
